services:
  booth-checker:
    image: ogunarmaya/booth-checker:latest
    volumes:
      - ./version:/root/booth-update-checker/version
      - ./archive:/root/booth-update-checker/archive
      - ./templates:/root/booth-update-checker/templates
      - ./config.json:/root/booth-update-checker/config.json
    networks:
      - booth-network
    depends_on:
      - booth-discord
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  booth-discord:
    image: ogunarmaya/booth-discord:latest
    volumes:
      - ./version:/root/booth-update-checker/version
      - ./config.json:/root/booth-update-checker/config.json
    networks:
      - booth-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  booth-network:
    driver: bridge