version: "3"

services:
  booth-update-checker:
    build: .
    container_name: booth-update-checker
    volumes:
      - ./checklist.json:/root/booth-update-checker/checklist.json
      - ./NanumGothic.ttf:/root/booth-update-checker/font.ttf
    restart: unless-stopped