services:
  booth-checker:
    image: ogunarmaya/booth-checker:latest
    volumes:
      - ./version:/root/boothchecker/version
      - ./archive:/root/boothchecker/archive
      - ./config.json:/root/boothchecker/config.json
    depends_on:
      - booth-discord
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  booth-discord:
    image: ogunarmaya/booth-discord:latest
    volumes:
      - ./version:/root/boothchecker/version
      - ./config.json:/root/boothchecker/config.json
    depends_on:
      - chrome
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chrome:
    image: selenium/standalone-chrome:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
