services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./version:/root/booth-update-checker/version
      - ./archive:/root/booth-update-checker/archive
    restart: unless-stopped